services:
    apache:
        build:
            context: .
        ports:
            - 80:80
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_ADMIN_USER=${DB_ADMIN_USER}
            - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
            - MOODLE_HOST=${MOODLE_HOST}
        depends_on:
            - mysql
        volumes:
            - moodle-data:/var/www/moodledata
        restart: always

    mysql:
        container_name: ${DB_HOST}
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_ADMIN_USER}
            MYSQL_PASSWORD: ${DB_ADMIN_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: ${DB_HOST}
        ports:
            - 8080:80
        depends_on:
            - mysql
volumes:
    db-data:
    moodle-data:
